### ISSUE TITLE
Log destinations

### ISSUE THREAD

**Issue by ChristinaGaitan** [papertrail/papertrail-heroku-plugin#17]
Hi, I'm trying to use the Remote Syslog Logger gem, I'm following [this guide]( https://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-ruby-on-rails-apps/ guide), but when I try to find my log destinations I can not see anything in my dashboard. Is there another way in which I can find my log destinations?

**Comment by johlym** [comment]
If you can't see anything, then you're likely using Papertrail as an add-on (purple top bar instead of blue) in which case that's normal. The destination is locked to the Heroku app in which the add-on was provisioned. 

Logging non-heroku sources would require setting up a standalone Papertrail account at https://papertrailapp.com, sending logs there, and re-configuring your Heroku app(s) [to send to it as well](https://help.papertrailapp.com/kb/hosting-services/heroku/#standalone).
